DROP DATABASE IF EXISTS cad_us;

CREATE DATABASE IF NOT EXISTS cad_us;

USE cad_us;

CREATE TABLE usuario (
    id_us BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(80) NOT NULL,
    numero VARCHAR(80) NOT NULL
);

